python -m torch.distributed.launch \
    --nproc_per_node=8 \
    --use_env main.py \
    --model deit_base_patch16_224 \
    --batch-size 128 \
    --data-path $1 \
    --output_dir experiment/gmp_8gpus_deit_base_density40_new \
    --dist_url 'tcp://127.0.0.1:23454' \
    --gmp \
    --sparsity 0.6 \
    --pruning_times 20 \
    --delta_t 6250 \
    --t_start 62500 \
    --num_workers $2